# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='previous_clan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Previous Clan'),
        ),
    ]
